//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.el_porvenirdb
{

    [Persistent(@"categoria")]
    public partial class Categoria : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fCategorias;
        [Size(50)]
        public string Categorias
        {
            get { return fCategorias; }
            set { SetPropertyValue<string>(nameof(Categorias), ref fCategorias, value); }
        }
        string fDescripcion;
        [Size(SizeAttribute.Unlimited)]
        public string Descripcion
        {
            get { return fDescripcion; }
            set { SetPropertyValue<string>(nameof(Descripcion), ref fDescripcion, value); }
        }
        [Association(@"MedicamentoReferencesCategoria")]
        public XPCollection<Medicamento> Medicamentoes { get { return GetCollection<Medicamento>(nameof(Medicamentoes)); } }
    }

}
