//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.el_porvenirdb
{

    [Persistent(@"factura_compra")]
    public partial class Factura_compra : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Empleado fId_Empleado;
        [Association(@"Factura_compraReferencesEmpleado")]
        public Empleado Id_Empleado
        {
            get { return fId_Empleado; }
            set { SetPropertyValue<Empleado>(nameof(Id_Empleado), ref fId_Empleado, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fNo_Factura;
        [Size(50)]
        public string No_Factura
        {
            get { return fNo_Factura; }
            set { SetPropertyValue<string>(nameof(No_Factura), ref fNo_Factura, value); }
        }
        Proveedor fId_Proveedor;
        [Association(@"Factura_compraReferencesProveedor")]
        public Proveedor Id_Proveedor
        {
            get { return fId_Proveedor; }
            set { SetPropertyValue<Proveedor>(nameof(Id_Proveedor), ref fId_Proveedor, value); }
        }
        Medicamento fId_Medicamento;
        [Association(@"Factura_compraReferencesMedicamento")]
        public Medicamento Id_Medicamento
        {
            get { return fId_Medicamento; }
            set { SetPropertyValue<Medicamento>(nameof(Id_Medicamento), ref fId_Medicamento, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        float fPrecio_Compra;
        public float Precio_Compra
        {
            get { return fPrecio_Compra; }
            set { SetPropertyValue<float>(nameof(Precio_Compra), ref fPrecio_Compra, value); }
        }
        float fTotal;
        public float Total
        {
            get { return fTotal; }
            set { SetPropertyValue<float>(nameof(Total), ref fTotal, value); }
        }
    }

}
