//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.el_porvenirdb
{

    [Persistent(@"factura_venta")]
    public partial class Factura_venta : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Empleado fId_Empleado;
        [Association(@"Factura_ventaReferencesEmpleado")]
        public Empleado Id_Empleado
        {
            get { return fId_Empleado; }
            set { SetPropertyValue<Empleado>(nameof(Id_Empleado), ref fId_Empleado, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fNo_Factura;
        [Size(50)]
        public string No_Factura
        {
            get { return fNo_Factura; }
            set { SetPropertyValue<string>(nameof(No_Factura), ref fNo_Factura, value); }
        }
        Inventario fId_Inventario;
        [Association(@"Factura_ventaReferencesInventario")]
        public Inventario Id_Inventario
        {
            get { return fId_Inventario; }
            set { SetPropertyValue<Inventario>(nameof(Id_Inventario), ref fId_Inventario, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        float fPrecio;
        public float Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<float>(nameof(Precio), ref fPrecio, value); }
        }
        decimal fIVA;
        public decimal IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<decimal>(nameof(IVA), ref fIVA, value); }
        }
        float fTotal;
        public float Total
        {
            get { return fTotal; }
            set { SetPropertyValue<float>(nameof(Total), ref fTotal, value); }
        }
    }

}
