//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.el_porvenirdb
{

    [Persistent(@"inventario")]
    public partial class Inventario : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Medicamento fId_Medicamento;
        [Association(@"InventarioReferencesMedicamento")]
        public Medicamento Id_Medicamento
        {
            get { return fId_Medicamento; }
            set { SetPropertyValue<Medicamento>(nameof(Id_Medicamento), ref fId_Medicamento, value); }
        }
        int fStock;
        public int Stock
        {
            get { return fStock; }
            set { SetPropertyValue<int>(nameof(Stock), ref fStock, value); }
        }
        float fPrecio_Compra;
        public float Precio_Compra
        {
            get { return fPrecio_Compra; }
            set { SetPropertyValue<float>(nameof(Precio_Compra), ref fPrecio_Compra, value); }
        }
        float fPrecio_Venta;
        public float Precio_Venta
        {
            get { return fPrecio_Venta; }
            set { SetPropertyValue<float>(nameof(Precio_Venta), ref fPrecio_Venta, value); }
        }
        DateTime fFecha_Vencimiento;
        public DateTime Fecha_Vencimiento
        {
            get { return fFecha_Vencimiento; }
            set { SetPropertyValue<DateTime>(nameof(Fecha_Vencimiento), ref fFecha_Vencimiento, value); }
        }
        [Association(@"Factura_ventaReferencesInventario")]
        public XPCollection<Factura_venta> Factura_ventas { get { return GetCollection<Factura_venta>(nameof(Factura_ventas)); } }
    }

}
