//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.el_porvenirdb
{

    [Persistent(@"laboratorio")]
    public partial class Laboratorio : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        string fNombre;
        [Size(50)]
        public string Nombre
        {
            get { return fNombre; }
            set { SetPropertyValue<string>(nameof(Nombre), ref fNombre, value); }
        }
        string fDireccion;
        [Size(SizeAttribute.Unlimited)]
        public string Direccion
        {
            get { return fDireccion; }
            set { SetPropertyValue<string>(nameof(Direccion), ref fDireccion, value); }
        }
        int fTelefono;
        public int Telefono
        {
            get { return fTelefono; }
            set { SetPropertyValue<int>(nameof(Telefono), ref fTelefono, value); }
        }
        Proveedor fId_Proveedor;
        [Association(@"LaboratorioReferencesProveedor")]
        public Proveedor Id_Proveedor
        {
            get { return fId_Proveedor; }
            set { SetPropertyValue<Proveedor>(nameof(Id_Proveedor), ref fId_Proveedor, value); }
        }
        [Association(@"MedicamentoReferencesLaboratorio")]
        public XPCollection<Medicamento> Medicamentoes { get { return GetCollection<Medicamento>(nameof(Medicamentoes)); } }
    }

}
