//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.Database
{

    [Persistent(@"detalleventa")]
    public partial class Detalleventa : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Factura_venta fId_FacturaVenta;
        [Association(@"DetalleventaReferencesFactura_venta")]
        public Factura_venta Id_FacturaVenta
        {
            get { return fId_FacturaVenta; }
            set { SetPropertyValue<Factura_venta>(nameof(Id_FacturaVenta), ref fId_FacturaVenta, value); }
        }
        Producto fId_Producto;
        [Association(@"DetalleventaReferencesProducto")]
        public Producto Id_Producto
        {
            get { return fId_Producto; }
            set { SetPropertyValue<Producto>(nameof(Id_Producto), ref fId_Producto, value); }
        }
        int fCantidad;
        public int Cantidad
        {
            get { return fCantidad; }
            set { SetPropertyValue<int>(nameof(Cantidad), ref fCantidad, value); }
        }
        float fPrecio;
        public float Precio
        {
            get { return fPrecio; }
            set { SetPropertyValue<float>(nameof(Precio), ref fPrecio, value); }
        }
        float fDescuento;
        public float Descuento
        {
            get { return fDescuento; }
            set { SetPropertyValue<float>(nameof(Descuento), ref fDescuento, value); }
        }
        int fIVA;
        public int IVA
        {
            get { return fIVA; }
            set { SetPropertyValue<int>(nameof(IVA), ref fIVA, value); }
        }
        float fTotal;
        public float Total
        {
            get { return fTotal; }
            set { SetPropertyValue<float>(nameof(Total), ref fTotal, value); }
        }
        float fSubTotal;
        public float SubTotal
        {
            get { return fSubTotal; }
            set { SetPropertyValue<float>(nameof(SubTotal), ref fSubTotal, value); }
        }
        Factura_venta fFactura_venta_Id;
        [Persistent(@"factura_venta_Id")]
        [Association(@"DetalleventaReferencesFactura_venta1")]
        public Factura_venta Factura_venta_Id
        {
            get { return fFactura_venta_Id; }
            set { SetPropertyValue<Factura_venta>(nameof(Factura_venta_Id), ref fFactura_venta_Id, value); }
        }
    }

}
