//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.Database
{

    [Persistent(@"factura_compra")]
    public partial class Factura_compra : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Empleado fId_Empleado;
        [Association(@"Factura_compraReferencesEmpleado")]
        public Empleado Id_Empleado
        {
            get { return fId_Empleado; }
            set { SetPropertyValue<Empleado>(nameof(Id_Empleado), ref fId_Empleado, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fNo_Factura;
        [Size(50)]
        public string No_Factura
        {
            get { return fNo_Factura; }
            set { SetPropertyValue<string>(nameof(No_Factura), ref fNo_Factura, value); }
        }
        int fId_Proveedor;
        public int Id_Proveedor
        {
            get { return fId_Proveedor; }
            set { SetPropertyValue<int>(nameof(Id_Proveedor), ref fId_Proveedor, value); }
        }
        float fTotal;
        public float Total
        {
            get { return fTotal; }
            set { SetPropertyValue<float>(nameof(Total), ref fTotal, value); }
        }
        [Association(@"DetallecompraReferencesFactura_compra")]
        public XPCollection<Detallecompra> Detallecompras { get { return GetCollection<Detallecompra>(nameof(Detallecompras)); } }
    }

}
