//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace FarmaciaElPorvenir.Database
{

    [Persistent(@"factura_venta")]
    public partial class Factura_venta : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>(nameof(Id), ref fId, value); }
        }
        Empleado fId_Empleado;
        [Association(@"Factura_ventaReferencesEmpleado")]
        public Empleado Id_Empleado
        {
            get { return fId_Empleado; }
            set { SetPropertyValue<Empleado>(nameof(Id_Empleado), ref fId_Empleado, value); }
        }
        DateTime fFecha;
        public DateTime Fecha
        {
            get { return fFecha; }
            set { SetPropertyValue<DateTime>(nameof(Fecha), ref fFecha, value); }
        }
        string fNo_Factura;
        [Size(50)]
        public string No_Factura
        {
            get { return fNo_Factura; }
            set { SetPropertyValue<string>(nameof(No_Factura), ref fNo_Factura, value); }
        }
        Cliente fId_Cliente;
        [Association(@"Factura_ventaReferencesCliente")]
        public Cliente Id_Cliente
        {
            get { return fId_Cliente; }
            set { SetPropertyValue<Cliente>(nameof(Id_Cliente), ref fId_Cliente, value); }
        }
        float fTotal_IVA;
        public float Total_IVA
        {
            get { return fTotal_IVA; }
            set { SetPropertyValue<float>(nameof(Total_IVA), ref fTotal_IVA, value); }
        }
        float fTotal_Factura;
        public float Total_Factura
        {
            get { return fTotal_Factura; }
            set { SetPropertyValue<float>(nameof(Total_Factura), ref fTotal_Factura, value); }
        }
        [Association(@"DetalleventaReferencesFactura_venta")]
        public XPCollection<Detalleventa> Detalleventas { get { return GetCollection<Detalleventa>(nameof(Detalleventas)); } }
    }

}
